* Textmind template

** Overview

Textmind uses Emacs to organize your prose, as GTD uses paper to organize your life.

Textmind is a Git repo holding the user's primary text exobrain.

This Git repo is a Textmind template. Use it to start your own Textmind.

Textmind needs the [[https://treefactor-docs.nfshost.com][Treefactor]] Emacs package to process the text thoughts one thinks daily.

The below installation instructions add my [[https://github.com/cyberthal/spacemacs-personal][personal Spacemacs layer]], which offers optional ergonomic improvements. Emacs experts may instead integrate Treefactor into their existing setup, and take what they like from my personal layer.

To learn more, read the [[https://bibliodemos-docs.nfshost.com][documentation]] for the Textmind demo.

Updated: [2020-01-03]

** Installation steps

*** clone Textmind template repo

**** remove any pre-existing files

rm -rf ~/1-Mansort/1-Textmind

**** clone the repo 

git clone https://gitgud.io/Bibliodemos/textmind-template.git ~/1-Mansort/1-Textmind
