* Textmind template

** Overview

Textmind is a way of using Emacs to organize your prose, as GTD is a way of using paper to organize your life.

Textmind is meant to be a Git monorepo containing the user's primary text exobrain.

This repo provides a Textmind template. You can use it to start your own Textmind instance.

Textmind requires the [[https://treefactor-docs.nfshost.com][Treefactor package]] to process the large volumes of text a human thinks daily.

The installation instructions below also include my [[https://github.com/cyberthal/spacemacs-personal][personal Spacemacs layer]]. It offers optional ergonomic improvements. Emacs experts can instead integrate Treefactor into their existing setup.

You can watch video demos of Textmind at my [[https://vimeo.com/cyberthal][Vimeo channel]]. More coming soon.

I will build a [[https://gitgud.io/Bibliodemos/textmind-my][public Textmind instance]] to show how Textmind organizes your life.

Updated: [2019-11-22]

** Installation steps

*** install Spacemacs

git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

*** install my Spacemacs personal layer

git clone https://github.com/cyberthal/spacemacs-personal.git ~/1-Mansort/2-Other-text/Github/Emacs/My/Personal

#+begin_src 
cd ~/1-Mansort/2-Other-text/Github/Emacs/My/Personal
./install-nixlike.sh
#+end_src

*** install Treefactor package manually

git clone https://github.com/cyberthal/treefactor.git ~/1-Mansort/2-Other-text/Github/Emacs/My/Treefactor/Prod

*** create Textmind directories expected by my personal Spacemacs layer

Otherwise Spacemacs startup will fail with an error.

#+begin_src 
mkdir -p ~/1-Mansort/1-Textmind/1-Agenda
mkdir -p ~/1-Mansort/1-Textmind/2-Linked
#+end_src

*** start Emacs to install new packages

**** If installation of many new packages fails, then:

edit init.el in my personal spacemacs layer so that
(setq package-check-signature nil)
instead of t

Once installation is complete, set it back to t.

*** set Hyper keybind on MS Natural Keyboard

1. open Karabiner Elements
2. Bind appkey to fn

(Keybind won't work through Synergy.)

*** clone Textmind template repo

**** remove any pre-existing files

rm -rf ~/1-Mansort/1-Textmind

**** clone the repo 

git clone https://gitgud.io/Bibliodemos/textmind-template.git ~/1-Mansort/1-Textmind
