* Textmind template

** Overview

Textmind uses Emacs to organize your prose, as GTD uses paper to organize your life.

Textmind is a Git repo holding the user's primary text exobrain.

This Git repo is a Textmind template. Use it to start your own Textmind.

Textmind needs the [[https://treefactor-docs.nfshost.com][Treefactor]] Emacs package to process the text thoughts a man thinks daily.

These installation instructions add my [[https://github.com/cyberthal/spacemacs-personal][personal Spacemacs layer]], which offers optional ergonomic improvements. Emacs experts may instead integrate Treefactor into their existing setup, and take what they like from my personal layer.

Watch demo videos of Textmind on [[https://vimeo.com/cyberthal][Vimeo]].

Here is a [[https://gitgud.io/Bibliodemos/textmind-my][demo Textmind instance]]. It shows how Textmind can organize your life.

Visit my [[https://discord.gg/bteSuV][Discord server]] to chat.

Updated: [2019-11-25]

** Installation steps

*** install Spacemacs

git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

*** install my Spacemacs personal layer

git clone https://github.com/cyberthal/spacemacs-personal.git ~/1-Mansort/2-Other-text/Github/Emacs/My/Personal

#+begin_src 
cd ~/1-Mansort/2-Other-text/Github/Emacs/My/Personal
./install-nixlike.sh
#+end_src

*** install Treefactor package manually

git clone https://github.com/cyberthal/treefactor.git ~/1-Mansort/2-Other-text/Github/Emacs/My/Treefactor/Prod

*** create Textmind directories expected by my personal Spacemacs layer

Otherwise Spacemacs startup will fail with an error.

#+begin_src 
mkdir -p ~/1-Mansort/1-Textmind/1-Agenda
mkdir -p ~/1-Mansort/1-Textmind/2-Linked
#+end_src

*** start Emacs to install new packages

**** If installation of many new packages fails, then:

edit init.el in my personal spacemacs layer so that
(setq package-check-signature nil)
instead of t

Once installation is complete, set it back to t.

*** set Hyper keybind on MS Natural Keyboard

1. open Karabiner Elements
2. Bind appkey to fn

(Keybind won't work through Synergy.)

*** clone Textmind template repo

**** remove any pre-existing files

rm -rf ~/1-Mansort/1-Textmind

**** clone the repo 

git clone https://gitgud.io/Bibliodemos/textmind-template.git ~/1-Mansort/1-Textmind
